AllCops:
  NewCops: disable
  Exclude:
    - 'vendor/bundle/**/*'
Style:
  Severity: error
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
